export const COMMENTS_SELECT_POST = 'COMMENTS_SELECT_POST';

export const COMMENTS_LOAD_POST_COMMENTS_START = 'COMMENTS_LOAD_POST_COMMENTS_START';
export const COMMENTS_LOAD_POST_COMMENTS_SUCCESS = 'COMMENTS_LOAD_POST_COMMENTS_SUCCESS';
export const COMMENTS_LOAD_POST_COMMENTS_FAIL = 'COMMENTS_LOAD_POST_COMMENTS_FAIL';